version: "3.0"
services:
  app:
    build: "./"
    command: ["npm", "start"]
    environment:
      - APPLICATION_NAME=mikko-monthly-money
      - LOG_LEVEL=info
      - OUTPUT_FILENAME=mikko-monthly-money.csv
      - OUTPUT_HEADINGS=true
    volumes:
      - ./:/home/node/app:delegated
