version: "3.0"
services:
  app:
    build: "./"
    command: ["npm", "start"]
    environment:
      - APPLICATION_NAME=mikko-monthly-money
      - LOG_LEVEL=info
    volumes:
      - ./:/home/node/app:delegated
