version: "3.0"
services:
  app:
    build: "./"
    command: ["npm", "start"]
    environment:
      - APPLICATION_BUILD_NUMBER=development
      - APPLICATION_NAME=mikko-monthly-money
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app:delegated
